obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_fp/
# Huaqin modify for ZQL1830-395 by zhaojunhai1 at 2018/7/26 start
obj-$(CONFIG_FOCAL_FP)	+= focal_fp/
# Huaqin modify for ZQL1830-395 by zhaojunhai1 at 2018/7/26 end
